---
title: "Project Introduction"
description: |
  My Senior Project: The impact of COVID-19 on the United States Cinema
author:
  - name: Spencer Carillo
date: 2022-05-25
output:
  distill::distill_article:
    self_contained: false
---

My project was to analyze the impact of the box office as well as the release of films in the United States before and after COVID-19. Since COVID-19 is a current problem affecting everyone around the world, I wanted to see at how it has affected the film industry. I saw first hand how it has affected theaters since day 1, and that is why I want to find out through research how it impacted the box office. I plan to use Box Office Mojo as well as the CDC Tracker to start with my data search. Wikipedia will also be a very helpful place for data. This project will help build my skills as a data analyst, using various visualization sites such as Power BI.

Week 1-2: I first collected data from a Wikipedia page that listed all the films impacted by COVID-19 and web scraped them through Python and then converted them into excel sheets. I then spent the next week cleaning this data to include only films that were produced in the United States, though there were many other films worldwide that were impacted by COVID-19. 

Week 3-4: I then tried to find how much box office was earned daily and though Box Office Mojo contained daily data, there was no way to gather it effectively. This led me to research other sites that might provide the required information. My search proved successful, and I discovered The Numbers, a website that also collected the box office earnings both domestically and worldwide, with the total listed at the bottom of each date.

Week 5-6: It was then I created an excel sheet that contained daily box office data from 2019 to 2022, as I wanted to do a comparison of what the box office was like before and after COVID-19. I also researched where to find the daily cases of COVID-19 in the United States. I successfully found the CDC COVID-19 tracker that provided reliable data.

Week 7-8: As I continued with my data, I found easier ways to input the required data, saving time that would have been wasted had I continued to do my earlier method. I then obtained my desired result of having not only the daily domestic box office from 2019 to 2022, but the daily COVID cases from 2020 till now. I then decided to open a Power BI to create my visuals.

